### ISSUE TITLE
Add option for extension to have delay, or remove delay of the initial palette reveal.

### ISSUE THREAD

**Issue by vitorgalvao** [tholman/palettab#1]
Currently, when we open a new tab the extension works a bit on getting the new palette and fonts, and then shows it. It’s fairly quick to do it, except when we consider that by opening a new tab I’ll likely want to navigate somewhere else, and do it fast.

Instead of `open new tab → download new palette → display palette`, the extension could be sped up if it worked like `open new tab → display previously downloaded palette → get new palette in background to show next time`.

**Comment by tholman** [comment]
You can now go back, if you saw something you liked, at the last minute!
