### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by wildskyf** [tholman/palettab#6]
Firefox support [WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) now.
Do you have any plan to provide Firefox version?
Or if you have no time, maybe I could help you to transplant this extension to Firefox. ;)
(By the way, I think there is some bug in Firefox WebExtension, so maybe we could use addon sdk currently, and do not use WebExtension until it is stable. )

**Comment by tholman** [comment]
Added & published (https://addons.mozilla.org/en-US/firefox/addon/palettab-newtab/)

**Comment by wildskyf** [comment]
Hi @tholman
I published it before
https://addons.mozilla.org/zh-TW/firefox/addon/palettab-fx/
I could add you as owner so that there will not be two the same add-on, and the number of user of this addon will not turn to zero. :)
